#!/usr/bin/env python3
"""Build-time packager for the two-part embeddable Windows distribution.

Produces the small ``app-<version>.zip`` (our source package only) that each
release ships; the heavy ``runtime/`` base is assembled by
``build_windows_embed.ps1``. This script is intentionally self-contained
(stdlib only, no import of the project) so it runs in any build environment and
is unit-testable on any OS.

The *runtime* half — applying an ``app-<version>.zip`` onto an install — lives in
the shipped package at ``telegram_download_chat.core.app_updater`` (so it is
available for in-app self-update), not here.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
import zipfile
from pathlib import Path
from typing import Optional

APP_PACKAGE = "telegram_download_chat"
VERSION_FILE = "version.txt"
_VERSION_MODULE = f"{APP_PACKAGE}/_version.py"
_HASH_CHUNK = 1024 * 1024


def compute_file_hash(path: Path) -> str:
    """Return the SHA-256 hex digest of ``path`` (printed so releases can publish it)."""
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(_HASH_CHUNK), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _iter_source_files(pkg_dir: Path):
    """Yield (path, arcname) for every shippable source file under ``pkg_dir``.

    Skips bytecode and ``__pycache__`` so the app zip carries only source.
    """
    pkg_dir = Path(pkg_dir)
    root = pkg_dir.name  # "telegram_download_chat"
    for path in sorted(pkg_dir.rglob("*")):
        if not path.is_file():
            continue
        if path.suffix == ".pyc" or "__pycache__" in path.parts:
            continue
        rel = path.relative_to(pkg_dir).as_posix()
        yield path, f"{root}/{rel}"


def build_app_zip(src_pkg_dir: Path, output_dir: Path, version: str) -> Path:
    """Build ``output_dir/app-<version>.zip`` from the app source package.

    The zip's top level is the *contents* of the installed ``app/`` directory:
    the ``telegram_download_chat`` package, a generated ``_version.py`` (so
    ``__version__`` resolves at runtime without setuptools-scm), and
    ``version.txt``. Bytecode is excluded.
    """
    src_pkg_dir = Path(src_pkg_dir)
    if not (src_pkg_dir / "__init__.py").is_file():
        raise FileNotFoundError(f"Not a Python package: {src_pkg_dir}")
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    zip_path = output_dir / f"app-{version}.zip"

    version_py = (
        "# Generated by package_embed.py for the embeddable build.\n"
        f"version = __version__ = {version!r}\n"
    )
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as archive:
        for path, arc in _iter_source_files(src_pkg_dir):
            if arc == _VERSION_MODULE:
                continue  # always regenerate below
            archive.write(path, arc)
        archive.writestr(_VERSION_MODULE, version_py)
        archive.writestr(VERSION_FILE, version)
    return zip_path


def main(argv: Optional[list] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    b = sub.add_parser(
        "build-app", help="Build app-<version>.zip from the source package"
    )
    b.add_argument(
        "src_pkg_dir", type=Path, help="Path to the telegram_download_chat package"
    )
    b.add_argument(
        "--version", required=True, help="Version string for the zip/markers"
    )
    b.add_argument(
        "--output-dir", type=Path, default=Path("dist"), help="Output directory"
    )

    args = parser.parse_args(argv)
    zip_path = build_app_zip(args.src_pkg_dir, args.output_dir, args.version)
    print(f"App zip: {zip_path}")
    print(f"SHA-256: {compute_file_hash(zip_path)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
