name: Build and Release

on:
  push:
    tags: 
      - 'v*'  # Trigger on version tags (e.g., v1.0.0)
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Run Windows build script
      run: |
        .\build_windows.ps1
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v3
      with:
        name: telegram-download-chat-windows
        path: dist/telegram-download-chat.exe
        if-no-files-found: error

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        brew install libmagic
        
    - name: Run macOS build script
      run: |
        bash build_macos.sh
    
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v3
      with:
        name: telegram-download-chat-macos
        path: dist/telegram-download-chat.dmg
        if-no-files-found: error

  release:
    name: Create Release
    needs: [build-windows, build-macos]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v3
      with:
        name: telegram-download-chat-windows
        path: artifacts/windows
    
    - name: Download macOS artifact
      uses: actions/download-artifact@v3
      with:
        name: telegram-download-chat-macos
        path: artifacts/macos
    
    - name: Get version from tag
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Release v${{ steps.get_version.outputs.version }}
        body: |
          Release v${{ steps.get_version.outputs.version }}
          
          ### Changes
          - Update changelog here
        draft: false
        prerelease: false
        files: |
          artifacts/windows/telegram-download-chat.exe
          artifacts/macos/telegram-download-chat.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
